EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Page Faults/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Available Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Committed Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Commit Limit'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Write Copies/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Transition Faults/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cache Faults/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Demand Zero Faults/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pages/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pages Input/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Page Reads/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pages Output/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pool Paged Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pool Nonpaged Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Page Writes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pool Paged Allocs'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pool Nonpaged Allocs'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Free System Page Table Entries'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cache Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cache Bytes Peak'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pool Paged Resident Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'System Code Total Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'System Code Resident Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'System Driver Total Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'System Driver Resident Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'System Cache Resident Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 12, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = '% Committed Bytes In Use'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Available KBytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Available MBytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Transition Pages RePurposed/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Free & Zero Page List Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Modified Page List Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Standby Cache Reserve Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Standby Cache Normal Priority Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'Memory', @vc_perfc_instance_name = '', @vc_perfc_name = 'Standby Cache Core Bytes'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RaSE Event Generator', @vc_perfc_instance_name = '', @vc_perfc_name = 'Producer Queue Lenght'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RaSE Event Generator', @vc_perfc_instance_name = '', @vc_perfc_name = 'Consumer Queue Lenght'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RaSE Event Generator', @vc_perfc_instance_name = '', @vc_perfc_name = 'Producer Thread Count'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RaSE Event Generator', @vc_perfc_instance_name = '', @vc_perfc_name = 'Consumer Thread Count'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RaSE Event Generator', @vc_perfc_instance_name = '', @vc_perfc_name = 'Is Quarantine'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Latency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 24, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Average Cybs Latency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 26, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Average Cybs LatencyBase'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Successful Requests/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Successful Requests'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Default Responses/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Default Responses'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Sync Timeouts/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Sync Timeouts'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Http Timeouts/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Http Timeouts'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Errors/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Errors'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Sync Open Requests'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Http Open Requests'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Rejected Requests/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME CyberSource Remote', @vc_perfc_instance_name = '', @vc_perfc_name = 'Cybs Rejected Requests'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Runtime Lookup Latency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 24, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Average Runtime Lookup Latency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 26, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Average Runtime Lookup LatencyBase'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Runtime Successful Requests/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Runtime Successful Requests'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Runtime Failed Requests/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Runtime Failed Requests'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Quova Loader Total Latency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Quova Db Loader Dat Latency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Quova Db Loader Ref Upload Latency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Quova Db Loader Anonfilelatency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Quova Db Loader Dat Rows'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Quova Db Loader Ref Upload Rows'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 4, @vc_perfc_category_name = 'RiME Quova', @vc_perfc_instance_name = '', @vc_perfc_name = 'Quova Db Loader Anonfile Rows'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_1', @vc_perfc_name = 'Processor Frequency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_1', @vc_perfc_name = '% of Maximum Frequency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 1, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_1', @vc_perfc_name = 'Processor State Flags'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_0', @vc_perfc_name = 'Processor Frequency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_0', @vc_perfc_name = '% of Maximum Frequency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 1, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_0', @vc_perfc_name = 'Processor State Flags'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_3', @vc_perfc_name = 'Processor Frequency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_3', @vc_perfc_name = '% of Maximum Frequency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 1, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_3', @vc_perfc_name = 'Processor State Flags'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_2', @vc_perfc_name = 'Processor Frequency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_2', @vc_perfc_name = '% of Maximum Frequency'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 1, @vc_perfc_category_name = 'Processor Performance', @vc_perfc_instance_name = 'PPM_Processor_2', @vc_perfc_name = 'Processor State Flags'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'OpsMgr SDK Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Client Connections'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'OpsMgr SDK Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Client Connections Using Cache'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'OpsMgr SDK Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Pending Client Type Cache Refresh Notifications'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Dirty State Notifications Failed'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Management Pack Requests Failed'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Avg. Management Pack Request (sec)'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 26, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Avg. Management Pack Request Base'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Change Notifications Failed'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Avg. Change Notification (sec)'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 26, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Avg. Change Notification Base'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Number Of Requests per Sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Number Of Active Requests'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Number Of Queued Requests'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 8, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Avg. Request Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Avg. Request Queue Wait Time (sec)'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 26, @vc_perfc_category_name = 'OpsMgr Config Service', @vc_perfc_instance_name = '', @vc_perfc_name = 'Avg. Request Queue Wait Time (sec) Base'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Current Disk Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 29, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% Disk Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 30, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 29, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% Disk Read Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 30, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk Read Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 29, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% Disk Write Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 30, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk Write Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk sec/Transfer'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk sec/Read'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk sec/Write'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Disk Transfers/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Disk Reads/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Disk Writes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Disk Bytes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Disk Read Bytes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Disk Write Bytes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 24, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk Bytes/Transfer'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 24, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk Bytes/Read'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 24, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Avg. Disk Bytes/Write'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 29, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% Idle Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Split IO/Sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Current Disk Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 29, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = '% Disk Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 30, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 29, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = '% Disk Read Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 30, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk Read Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 29, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = '% Disk Write Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 30, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk Write Queue Length'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk sec/Transfer'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk sec/Read'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 22, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk sec/Write'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Disk Transfers/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Disk Reads/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Disk Writes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Disk Bytes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Disk Read Bytes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Disk Write Bytes/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 24, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk Bytes/Transfer'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 24, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk Bytes/Read'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 24, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Avg. Disk Bytes/Write'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 29, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = '% Idle Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'PhysicalDisk', @vc_perfc_instance_name = '0 C: D:', @vc_perfc_name = 'Split IO/Sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 17, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% Processor Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% User Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% Privileged Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'Interrupts/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% DPC Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% Interrupt Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'DPCs Queued/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'DPC Rate'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% Idle Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% C1 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% C2 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = '% C3 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'C1 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'C2 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '_Total', @vc_perfc_name = 'C3 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 17, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% Processor Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% User Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% Privileged Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = 'Interrupts/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% DPC Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% Interrupt Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = 'DPCs Queued/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = 'DPC Rate'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% Idle Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% C1 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% C2 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = '% C3 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = 'C1 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = 'C2 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '2', @vc_perfc_name = 'C3 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 17, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% Processor Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% User Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% Privileged Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = 'Interrupts/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% DPC Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% Interrupt Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = 'DPCs Queued/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = 'DPC Rate'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% Idle Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% C1 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% C2 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = '% C3 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = 'C1 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = 'C2 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '3', @vc_perfc_name = 'C3 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 17, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% Processor Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% User Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% Privileged Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = 'Interrupts/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% DPC Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% Interrupt Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = 'DPCs Queued/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = 'DPC Rate'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% Idle Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% C1 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% C2 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = '% C3 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = 'C1 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = 'C2 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '0', @vc_perfc_name = 'C3 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 17, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% Processor Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% User Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% Privileged Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = 'Interrupts/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% DPC Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% Interrupt Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 10, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = 'DPCs Queued/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 3, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = 'DPC Rate'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% Idle Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% C1 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% C2 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 14, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = '% C3 Time'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = 'C1 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = 'C2 Transitions/sec'
EXEC spm_InsertPerfCounterReference{}VERSION_SUFFIX @i_perfc_type_id = 11, @vc_perfc_category_name = 'Processor', @vc_perfc_instance_name = '1', @vc_perfc_name = 'C3 Transitions/sec'
