using System;
using System.Data;
using System.Text;
using System.Xml.Serialization;

///
/// This file is generated by private\Monitoring\CodeGen\codegen.py
/// Please don't edit this file.
///

namespace Dummy.Monitoring.MonitoringLib.DO
{
    public partial class $dataObjectName : DOBase
    {
        #region Properties
$dataObjectProperties
        #endregion

        #region Constructors
        public $dataObjectName()
            : base()
        {
        }

        public $dataObjectName(DataRow row)
        {
            Fill(row);
        }
        #endregion
        
        #region Public Methods
        public override FillStatus Fill(DataRow row)
        {
            return Fill(row, null);
        }

        public override FillStatus Fill(DataRow row, string prefix)
        {
            string columnName;
            bool allFieldsMet = true;
$dataObjectRowToProperties
            IsDirty = false;
            RowFillStatus = allFieldsMet ? FillStatus.ALL : FillStatus.PARTIAL;
            return RowFillStatus;
        }

        public override void PushDataRow(DataTable dataTable)
        {
            DataRow dataRow = dataTable.NewRow();
$dataObjectRowToDataRows
            dataTable.Rows.Add(dataRow);
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
$dataObjectStrings
            return sb.ToString();
        }

        public $dataObjectName CopyTo($dataObjectName newInstance)
        {
$dataObjectClones
            newInstance.IsDirty = this.IsDirty;
            return newInstance;
        }

        public $dataObjectName Clone()
        {
            return CopyTo(new $dataObjectName());
        }
        #endregion

        #region Extra
$dataObjectExtra
        #endregion
    }
}
