using System.Collections.Generic;
using System.Text.RegularExpressions;
using Dummy.Monitoring.MonitoringInterface.Common;

///
/// This file is generated by private\Monitoring\CodeGen\codegen.py
/// Please don't edit this file.
///

namespace Dummy.Monitoring.MonitoringInterface.Configurations
{
    public partial interface IGlobalConfiguration
    {
        SortedDictionary<string, string> ConfigurationDictionary { get; }
$iGlobalConfiguration
        Regex[] PerfCounterFilters { get; }
        Dictionary<int, PropertyTypeEnum> PropertyTypeIDToPropertyTypeEnumDictionary { get; }
        Dictionary<PropertyTypeEnum, int> PropertyTypeEnumToPropertyTypeIDDictionary { get; }
        Dictionary<int, int> PerfCounterTypeDictionary { get; }
        Dictionary<int, PropertyValueStyle> PerfCounterTypeValueToPropertyValueStyleDictionary { get; }
        Dictionary<int, string> DataCenterIDToDataCenterNameDictionary { get; }
        Dictionary<int, int> ServerIDToDataCenterIDDictionary { get; }
        Dictionary<int, string> ServerIDToDataCenterNameDictionary { get; }
        Dictionary<int, string> ServerIDToServerRoleNameDictionary { get; }
        Dictionary<int, string> ServerIDToServerNameDictionary { get; }
        Dictionary<int, bool> ServerIDToServerEnabledDictionary { get; }
        Dictionary<int, string> PartnerIDToPartnerNameDictionary { get; }
        Dictionary<int, string> UserGroupIDToUserGroupNameDictionary { get; }
        HashSet<int> UserGroupSystemAdminSet { get; }
        HashSet<int> UserGroupReportUserSet { get; }
        HashSet<int> UserGroupReportGuestSet { get; }
    }
}