using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Dummy.Monitoring.MonitoringInterface.Common;
using Dummy.Monitoring.MonitoringInterface.Configurations;
using Dummy.Monitoring.MonitoringLib.DO;

///
/// This file is generated by private\Monitoring\CodeGen\codegen.py
/// Please don't edit this file.
///

namespace Dummy.Monitoring.MonitoringLib.Models.InterfaceImplements.Configurations
{
    public class GlobalConfiguration : IGlobalConfiguration
    {
        public GlobalConfiguration()
        {
        }

        private SortedDictionary<string, string> _configurationDictionary;
        public SortedDictionary<string, string> ConfigurationDictionary
        {
            get { return _configurationDictionary; }
            set { _configurationDictionary = value; }
        }

$globalConfiguration

        public void UpdateConfigCommon()
        {
$updateGlobalConfiguration
        }

        private List<Regex> _perfCounterFilters;
        public Regex[] PerfCounterFilters
        {
            get { return _perfCounterFilters.ToArray(); }
            set { _perfCounterFilters = new List<Regex>(value); }
        }

        private Dictionary<int, int> _perfCounterTypeDictionary;
        public Dictionary<int, int> PerfCounterTypeDictionary
        {
            get { return _perfCounterTypeDictionary; }
            set { _perfCounterTypeDictionary = value; }
        }

        private Dictionary<int, PropertyValueStyle> _perfCounterTypeValueToPropertyValueStyleDictionary;
        public Dictionary<int, PropertyValueStyle> PerfCounterTypeValueToPropertyValueStyleDictionary
        {
            get { return _perfCounterTypeValueToPropertyValueStyleDictionary; }
            set { _perfCounterTypeValueToPropertyValueStyleDictionary = value; }
        }

        private Dictionary<PropertyTypeEnum, int> _propertyTypeEnumToPropertyTypeIDDictionary;
        public Dictionary<PropertyTypeEnum, int> PropertyTypeEnumToPropertyTypeIDDictionary
        {
            get { return _propertyTypeEnumToPropertyTypeIDDictionary; }
            set { _propertyTypeEnumToPropertyTypeIDDictionary = value; }
        }

        private Dictionary<int, PropertyTypeEnum> _propertyTypeIDToPropertyTypeEnumDictionary;
        public Dictionary<int, PropertyTypeEnum> PropertyTypeIDToPropertyTypeEnumDictionary
        {
            get { return _propertyTypeIDToPropertyTypeEnumDictionary; }
            set { _propertyTypeIDToPropertyTypeEnumDictionary = value; }
        }

        private Dictionary<int, string> _dataCenterIDToDataCenterNameDictionary;
        public Dictionary<int, string> DataCenterIDToDataCenterNameDictionary
        {
            get { return _dataCenterIDToDataCenterNameDictionary; }
            set { _dataCenterIDToDataCenterNameDictionary = value; }
        }

        private Dictionary<int, int> _serverIDToDataCenterIDDictionary;
        public Dictionary<int, int> ServerIDToDataCenterIDDictionary
        {
            get { return _serverIDToDataCenterIDDictionary; }
            set { _serverIDToDataCenterIDDictionary = value; }
        }

        private Dictionary<int, string> _serverIDToDataCenterNameDictionary;
        public Dictionary<int, string> ServerIDToDataCenterNameDictionary
        {
            get { return _serverIDToDataCenterNameDictionary; }
            set { _serverIDToDataCenterNameDictionary = value; }
        }

        private Dictionary<int, string> _serverIDToServerRoleNameDictionary;
        public Dictionary<int, string> ServerIDToServerRoleNameDictionary
        {
            get { return _serverIDToServerRoleNameDictionary; }
            set { _serverIDToServerRoleNameDictionary = value; }
        }

        private Dictionary<int, string> _serverIDToServerNameDictionary;
        public Dictionary<int, string> ServerIDToServerNameDictionary
        {
            get { return _serverIDToServerNameDictionary; }
            set { _serverIDToServerNameDictionary = value; }
        }

        private Dictionary<int, bool> _serverIDToServerEnabledDictionary;
        public Dictionary<int, bool> ServerIDToServerEnabledDictionary
        {
            get { return _serverIDToServerEnabledDictionary; }
            set { _serverIDToServerEnabledDictionary = value; }
        }

        private Dictionary<int, string> _partnerIDToPartnerNameDictionary;
        public Dictionary<int, string> PartnerIDToPartnerNameDictionary
        {
            get { return _partnerIDToPartnerNameDictionary; }
            set { _partnerIDToPartnerNameDictionary = value; }
        }

        private Dictionary<int, string> _userGroupIDToUserGroupNameDictionary;
        public Dictionary<int, string> UserGroupIDToUserGroupNameDictionary
        {
            get { return _userGroupIDToUserGroupNameDictionary; }
            set { _userGroupIDToUserGroupNameDictionary = value; }
        }

        private HashSet<int> _userGroupSystemAdminSet;
        public HashSet<int> UserGroupSystemAdminSet
        {
            get { return _userGroupSystemAdminSet; }
            set { _userGroupSystemAdminSet = value; }
        }

        private HashSet<int> _userGroupReportUserSet;
        public HashSet<int> UserGroupReportUserSet
        {
            get { return _userGroupReportUserSet; }
            set { _userGroupReportUserSet = value; }
        }

        private HashSet<int> _userGroupReportGuestSet;
        public HashSet<int> UserGroupReportGuestSet
        {
            get { return _userGroupReportGuestSet; }
            set { _userGroupReportGuestSet = value; }
        }
    }
}